class Invar(object):

    @classmethod
    def entity_tagging(cls):
        return {
            'America'       :['White House', 'America','Congress', 'Washington', 'United States of America','U.S.','U.S.A.','USA','United States','American','Americans'],
            'alt_media'     :['4chan', 'Breitbart', 'AlexJones', 'infowar','GlennBeck','RushLimbaugh','MiloYiannopoulos','StefanMolyneux','SteveBannon','Wikileaks','Fox News'],
            'msm_media'     :['New York Times', 'NYT','NYTimes', 'MSM', 'JohnOliver','JonStewart','RachelMaddow','cnn','HuffingtonPost','abc','cbs','nbc','msnbc','BBC','CLINTON NEWS NETWORK'],
            'race'          :['black_lives_matter','African-American','dindunuffin','African American','Asian','black','white','Caucasian','Hispanic','Latino','Indian'],
            'Brexit'        :['Brexit', 'Nigel Farage', 'Nigel Farrage', 'Farage', 'Farrage','Brexpats','UKIP'],
            'BarackObama'   :['BarackObama','Michelle Obama'],
            'Communism'     :['FidelCastro','cuba','Cuban', 'communism','soviet union','ussr','socialism','Bolshevik','Soviet'],
            'Christian'     :['pope', 'Jesus','Bible','Christendom','Christianity','Church','Messiah','Satan','Satanism','Christian','Catholic','Catholicism','Catholics'],
            'Democrats'     :['Democratic Party', 'DNC', 'Demmies','Democrap','Demokkkrat','Democrappies','Democrates','Democrats','Dems','Libs','Libtard','Libtards'],
            'DonaldTrump'   :['DonaldTrump','GodEmperorTrump','IvankaTrump','EricTrump','MelaniaTrump','MAGA'],
            'Europe'        :['GeertWilders','MarineLepen','AngelaMerkel','Berlusconi','europe','European','german','Austrian','British','Brits','UK','France', 'French','Ireland', 'Irish','Italy', 'Italian','Poland', 'Pole','Polish','Spain','Spanish','Swede','Sweden','Swedish','Britain'],
            'Events'        :['JamesComey','JulianAssange','wikileaks','ferguson','Benghazi','Occupy','Pussy'],
            'evil_people'   :['GeorgeSoros','MarkZuckerberg','MichaelMoore','Rothschild'],
            'other_countries':['Californian','California','Canada','Trudeau','Canadian','Chinese','China','FidelCastro','cuba','Cuban'],
            'HillaryClinton':['HillaryClinton'],
            'left_orgs'     :['ADL','ACLU','Panned Parenthood','Parenthood','Clinton Foundation','LGBT','LGBTQ'],
            'Islam'         :['AlQueda', 'Islam','Jihad','Koran','Coran','Coranic','Ramadan','Allah','Quran','Sharia','Muslim','Arab','Arabs','islamic','Islamist'],
            'Judaism'       :['Jew','Jews', 'Jewish','Ashkenazi','Israeli', 'goyim', 'goy', 'holocaust', 'holohoax','Israel','Palestinian','Zionism','Zionist'],
            'Memewar'       :['Kek','Meme Magic', 'Meme Magick', 'Meme War', 'Meme Wars', 'MemeMagic', 'Memecraft','Pepe'],
            'Mexico'        :['Mexico','wall','mexican'],
            'Nazi'          :['National Socialism', 'kkk', 'swastika', 'DavidDuke', 'Aryan','Aryans', 'Neo-Nazi', 'Nazi Germany','Nazi', 'Fascism','Fascist','Fascists','Goebbels','HEIL','Fuhrer','Trumpreich','Hitler','Holohoax','Adolf Hitler','Adolf','Mein','Mein Fuehrer','Mein Junge','Mein Kampf','Mussolini','Fuhrer','Reich'],
            'politician_dems':['BillClinton','BernieSanders','TimKaine','Elizabeth Warren','Pocahantas','Pocahontas','Joe Biden', 'Biden'],
            'politician_reps':['RNC', 'ChrisChristie','GeorgeBush','GOP','JebBush','MikePence','RonaldReagan','SarahPalin','TedCruz','Dick Cheney','Cheney','John McCain','Mitt Romney','Romney','Kasich','Ben Carson','Dr Carson','Conservative','Republican'],
            'Russia'        :['Putin','Russia','Russian'],
            'war'           :['Afghan','Afghanistan','Assad','Syria','Irak','Syrian','Aleppo'],
        }


    @classmethod
    def entity_persons(cls):
        return {
            'AlexJones':['Alex Jones'],
            'AlQueda':['Al Queda','Al Qaida','Isis','Al-Qaeda','Al Qaeda'],
            'AngelaMerkel':['Angela Merkel','Merkel'],
            'BarackObama':['Barack Hussein Obama', 'Barack Obama','Malik Obama','Obama'],
            'BillClinton':['BillClinton','Bill Clinton','husband Bill'],
            'BernieSanders':['Bernie Sanders','Bernie','Sanders','Berniecucks','Bernies'],
            'ChrisChristie':['Chris Christie'],
            'DavidDuke':['David Duke','Duke'],
            'DonaldTrump': ['Donald Trump', 'Trump', 'God King', 'God Trump', 'God-Emperor', 'EMPEROR TRUMP', 'Emperor Palpatine', 'Emperor Trump', 'Donald J. Trump', 'Donald J Trump', 'Drumpf', 'Baron Trump', 'The Emperor', 'Der Donald', 'Lord Emperor', 'Fuhrer Trump', '#Trump', 'Adolf Trump', 'Adolf Trumper', 'Donaldus Magnus', 'Trumpachu', 'Trumpaloompas', 'Trumpamaniacs', 'Trumpanzee', 'Trumpasaurus Rex', 'Trumpboner', 'Trumpborne', 'Trumpbot', 'Trumpcloaks', 'Trumpen Reich', 'Trumpenreich', 'Trumpenverse', 'Trumpepe', 'Trumper', 'Trumpeteer', 'Trumpeter', 'Trumpettes', 'Trumpf', 'Trumpfucker', 'Trumph', 'Trumphalla', 'Trumpidari', 'Trumpinator', 'Trumpinreich', 'Trumpire', 'Trumpis', 'Trumpivia', 'Trumpkin', 'Trumpkins', 'Trumplon', 'Trumpman', 'Trumpmanía', 'Trumpmas', 'Trumpmeister', 'Trumpmoji', 'Trumpo', 'Trumpophiles', 'Trumpover', 'Trumpp', 'Trumps', 'Trumpsherd', 'Trumpster', 'Trumpstika', 'Trumptrain', 'Trumpulus ', 'Caesar', 'Trumpumvirate', 'Trumpus','DJT', 'Drumft','Drumpf'],
            'EricTrump':['Eric Trump'],
            'FidelCastro':['Fidel Castro','Castro','Fidel'],
            'GeorgeBush':['Bush','George W Bush','George Bush','George W. Bush'],
            'GeorgeSoros':['George Soros','Soros'],
            'GeorgeTakei': ['George Takei','Takei'],
            'GlennBeck':['Glenn Beck'],
            'GodEmperorTrump':['God Emperor Trump'],
            'HillaryClinton':['Shillary','Hillary Clinton','Crooked Hillary','Killary Clinton', 'Hillary','Clinton','Hilary','Killary','HRC','Killiary'],
            'IvankaTrump':['Ivanka Trump','Ivanka'],
            'JamesComey': ['James Comey','Comey'],
            'JebBush ':['Jeb Bush'],
            'JohnOliver':['John Oliver'],
            'JulianAssange': ['Julian Assange','Assange'],
            'JonStewart':['Jon Stewart'],
            'MarineLepen':['Marine Lepen', 'Marine Le Pen','LePen', 'lepenn','Marine','Le Pen','Le Penn'],
            'MarkZuckerberg':['Mark Zuckerberg','Zuckerberg','zucc','Mark Cuckerberg','Mark Fuckerberg','Cuckerberg','Cuckerbrg', 'Suckerberg','Fuckerberg','Mark Zuck','Zuck'],
            'MichaelMoore':['Michael Moore'],
            'MelaniaTrump':['Melania Trump','Melania'],
            'MiloYiannopoulos':['Milo Yiannopoulos','Yiannopoulos','Milo'],
            'MikePence':['Mike Pence','Pence'],
            'Putin':['Putin'],
            'RachelMaddow': ['Rachel Madcow', 'Rachel Maddow','Maddow','Madcow'],
            'RonaldReagan':['Ronald Reagan','Reagan'],
            'Rothschild':['Rothchild','Rothchilds','Rothschild','Rothschilds'],
            'SarahPalin':['Sarah Palin','Palin'],
            'StefanMolyneux':['Stefan Molyneux','Molyneux'],
            'SteveBannon':['Steve Bannon','Bannon'],
            'TedCruz':['Ted Cruz','Cruz'],
            'TimKaine':['Tim Kaine','Kaine'],
            'HuffingtonPost' :['Huff Po','HuffPo','Huffpost','Huff Post','Huffington'],
        }




    @classmethod
    def regex_translate(cls):
        return {
            'lol(ol)+': 'lol',
            "xdd+":"xdd",
            'yes+': 'yes',
            'hm+': 'hmm',
            'ohh+': 'oh',
            'yu+ge': 'yuge',
            'lmao+': 'lmao',
            'lmfao+': 'lmao',
            '(haha|ahah)(a|h)+': 'haha'
        }


    @classmethod
    def lingo(cls):
        return  {
            "lel":"lol",
            # "allahu akbar":"allahu_akbar",
            "merica":"america",
            "keks":"kek",
            "lulz":"lol",
            "lyin":"lying",
            "establishmment":"establishment",
            "jr": "junior",
            "pls": "please",
            "plz": "please",
            "xd": "lol",
            "cucks": "cuck",
            "harambe":"harambe_gorilla",
            "hillarys":"hillary",
            "killary":"bengazi_hillari",
            "fuckin":"fucking",
            "doesnt": "does not",
            "clintons": "clinton",
            "fb":"facebook",
            "tv":"television",
            "obamas": "obama",
            "swj":"social_justice_warrior",
            "sjws":"social_justice_warrior",
            "sjw":"social_justice_warrior",
            "bruh":"brother",
            "dems":"democrates",
            "btw":"by the way",
            "blm":"black_lives_matter",
            "trumppence": "trump pence",
            "trumptrain": "trump train",
            "nigga":"nigger",
            "lolol":"lol",
            "cuz":"because",
            "nah":"no",
            "cmon": "come_on",
            "come on": "come_on",
            "admins":"admin",
            "el rato":"ted_cruz",
            "rato":"ted_cruz",
            "bs": "bullshit",
            "photoshopped":"photoshop",
            "dindu nuffin": "dindunuffin",
            "ffs": "for_fuck_sake",
            "guac bowl merchant":"Jeb Bush guac",
            "pepes":"pepe",
            "ppl":"people",
            "putins":"putin",
            "quran":"coran",
            "rekt":"wrecked",
            "aids skrillex":"aids_skrillex",
            "tru":"true",
            "bwhaha":"haha",
            "bhaha":"haha",
            "fucken":"fuck",
            "atleast":"at least",
            "deus vult":"deusvult",

        }
    @classmethod
    def contractions(cls):
        return  {
            "'em":"them",
            "'ol":"old",
            "ain't": "am not",
            "aint": "am not",
            "aren't": "are not",
            "thatll":"that will",
            "arent": "are not",
            "can't": "cannot",
            "cant": "cannot",
            "could've": "could have",
            "couldn't": "could not",
            "couldnt": "could not",
            "didn't": "did not",
            "didnt": "did not",
            "doesn't": "does not",
            "doesnt": "does not",
            "don't": "do not",
            "dont": "do not",
            "gonna":"going to",
            "hadn't": "had not",
            "hadnt": "had not",
            "hasn't": "has not",
            "hasnt": "has not",
            "haven't": "have not",
            "havent": "have not",
            "he'd": "he had",
            "hed": "he had",
            "he'll": "he will",
            "hell": "he will",
            "he's": "he is",
            "hes": "he is",
            "i'd": "I would",
            "id": "I would",
            "i'll": "I will",
            "ill": "I will",
            "i'm": "I am",
            "im": "I am",
            "i've": "I have",
            "ive": "I have",
            "isn't": "is not",
            "isnt": "is not",
            "it'll": "it will",
            "itll": "it will",
            "it's": "it is",
            "its": "it is",
            "let's": "let us",
            "lets": "let us",
            "she'd": "she she would",
            "shed": "she she would",
            "she'll": "she will",
            "shell": "she will",
            "she's": "she is",
            "shes": "she is",
            "that's": "that has",
            "thats": "that has",
            "there's": "there is",
            "theres": "there is",
            "they'd": "they would",
            "theyd": "they would",
            "they'll": "they will",
            "theyll": "they will",
            "they're": "they are",
            "theyre": "they are",
            "they've": "they have",
            "theyve": "they have",
            "whats":"what is",
            "wanna": "want to",
            "wasnt": "was not",
            "wasn't": "was not",
            "we'll": "we will",
            "well": "we will",
            "we're": "we are",
            "were": "we are",
            "we've": "we have",
            "weve": "we have",
            "weren't": "were not",
            "werent": "were not",
            "who'll": "who who will",
            "wholl": "who who will",
            "who's": "who is",
            "whos": "who is",
            "won't": "will not",
            "wont": "will not",
            "wouldn't": "would not",
            "wouldnt": "would not",
            "you'll": "you will",
            "youll": "you will",
            "you're": "you are",
            "youre": "you are",
            "you've": "you have",
            "youve": "you have",
            "1st": "first",
            "2nd": "second",
            "3rd": "third",
            "4th": "fourth",
            "5th": "fifth",
            "6th": "sixth",
            "7th": "seventh",
            "dont": "do not",
            "havent": "have not",
            "i've": "I have",
            "ive": "I have",
            "they're" : "they are",
            "wouldn't": "would not",
            "would've":"would have",
            "shouldn't": "should not",
            "shouldn    t": "should not",
            "shouldve": "should have",
            "should've": "should have",
            "i'm": "I am",
            "you'd":"you would",
            "you're":"you are",
            "itd":"it would",
            "alot":"a lot",
            "adl":"anti_defamation_league",
            "thot":"that_ho_over_there",
            "thots":"that_ho_over_there",
            }

    @classmethod
    def extra_stopwords(cls):
        return ['say','get','would','could','make','one','going',
                'actually', 'also', 'always', 'another', 'anyone', 'anything',
                'back', 'bad', 'come', 'day', 'day', 'done', 'even', 'ever', 'every',
                'everyone', 'fuck', 'fucking', 'getting', 'give', 'going', 'good',
                'got', 'great', 'guy', 'guys', 'haha', 'hard', 'keep', 'know', 'let',
                'like', 'literally', 'lmao', 'lol', 'look', 'lot', 'man', 'many',
                'maybe', 'mean', 'much', 'need', 'never', 'next', 'nothing', 'one',
                'point', 'probably', 'prsn', 'real', 'really', 'said', 'saying', 'see','saw',
                'shit', 'someone', 'something', 'still', 'stop', 'stupid', 'sure',
                'take', 'talking', 'tell', 'thing', 'things', 'think', 'thought',
                'time', 'true', 'trying', 'two', 'want', 'way', 'wrong', 'yeah', 'yes',
                'able', 'absolutely', 'actual', 'agree', 'alex', 'almost', 'already',
                'around ', 'ask', 'ass', 'awesome', 'based', 'beautiful', 'bring',
                'bunch', 'call', 'called', 'calling', 'came', 'care', 'clearly',
                'coming', 'comment', 'comments', 'cool ', 'dick', 'either', 'else',
                'end', 'enough', 'everything', 'feel ', 'fucked', 'full', 'gave',
                'gets', 'goes', 'guess', 'hey', 'idiot', 'instead', 'kind', 'last',
                'least', 'less', 'little', 'live', 'lmfao ', 'long', 'looking',
                'looks', 'made ', 'makes ', 'making', 'may', 'middle', 'might',
                'must', 'needs ', 'obviously', 'okay', 'omg', 'ones', 'please',
                'put', 'quite', 'rather', 'read ', 'saw', 'says', 'seem ', 'seems',
                'seen', 'sent', 'seriously', 'show', 'since', 'sounds', 'supposed',
                'taking ', 'thinking', 'tho', 'told ', 'took', 'totally', 'using ',
                'wait', 'went ', 'whatever', 'whats', 'wow', 'wtf', 'yet','xdd','omfg'
        ]










